# Generated by Django 3.1.5 on 2021-07-10 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SAMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CS1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='0', max_length=50)),
                ('week_1', models.CharField(default='0', max_length=10)),
                ('week_2', models.CharField(default='0', max_length=10)),
                ('week_3', models.CharField(default='0', max_length=10)),
                ('week_4', models.CharField(default='0', max_length=10)),
                ('week_5', models.CharField(default='0', max_length=10)),
                ('week_6', models.CharField(default='0', max_length=10)),
                ('week_7', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fourth_Year_Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('CS1', 'CS1'), ('CS2', 'CS2'), ('CS3', 'CS3'), ('CS4', 'CS4'), ('CS5', 'CS5'), ('CS6', 'CS6'), ('CS7', 'CS7')], max_length=20, unique=True)),
                ('professor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAMS.professor', to_field='Name')),
            ],
        ),
        migrations.CreateModel(
            name='LectureSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.IntegerField()),
                ('day', models.CharField(choices=[('Sat', 'Sat'), ('Sun', 'Sun'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri')], max_length=10)),
                ('time', models.CharField(choices=[('09-00', '09-00'), ('10.30', '10.30'), ('12-00', '12-00'), ('13.30', '13.30'), ('15-00', '15-00')], max_length=10)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lecture.fourth_year_subjects', to_field='subject')),
            ],
        ),
    ]
